title: "Lil' Car"
description: ""
baseurl: ""
url: ""

source: src
destination: build

exclude:
  - audio/originals
  - css
  - img/svg
  - img/template
  - python

plugins:
  - jekyll-minifier

jekyll-minifier:
  compress_javascript: true